title: "Juan Pavez | Blog"
description: "Blog técnico y personal de Juan Pavez"
email: juanpavez@ejemplo.com
url: "https://juandrespq.github.io"
repository: juandrespq/juandrespq.github.io
baseurl: ""
share: false

# Tema
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dirt"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-include-cache

# Configuración de defaults
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# Paginación
paginate: 5
paginate_path: /page:num/

author:
  name   : "Juan Pavez"
  avatar : "/assets/images/avatar.jpg"
  bio    : "Ingeniero, desarrollador y creador de soluciones."

# Navigation
navigation:
  - title: "Inicio"
    url: /
  - title: "Posts"
    url: /posts/
  - title: "Categorías"
    url: /categories/
  - title: "Etiquetas"
    url: /tags/
  - title: "Acerca de"
    url: /about/

# Footer adicional
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/juandrespq"