title: "Juan Pavez | Blog"
description: "Blog de tecnología, desarrollo y proyectos personales."
email: juanpavez@ejemplo.com
url: "https://juandrespq.github.io"
baseurl: ""

# Usa el tema como remote_theme en lugar de theme:
remote_theme: mmistakes/minimal-mistakes@4.24.0

author:
  name   : "Juan Pavez"
  avatar : "/assets/images/avatar.jpg"
  bio    : "Ingeniero, creador y entusiasta de la tecnología."

show_excerpts: true
paginate: 5
paginate_path: /page:num/

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

navigation: main

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true