title: "Juan Pavez | Blog"
description: "Blog técnico y personal de Juan Pavez"
email: juanpavez@ejemplo.com
url: "https://juandrespq.github.io"
repository: juandrespq/juandrespq.github.io
baseurl: ""

# Usa el tema remoto
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default # o el skin que prefieras

# Activa el tema remoto en GitHub Pages
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Menú lateral
navigation: main

author:
  name   : "Juan Pavez"
  avatar : "/assets/images/avatar.jpg"
  bio    : "Ingeniero, desarrollador y creador de soluciones."

# Configurar layout y sidebar para posts y páginas
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
    values:
      author_profile: true

show_excerpts: true
paginate: 5
paginate_path: /page:num/
